### ISSUE TITLE
Server not permitting communication! Check URL.

### ISSUE THREAD

**Issue by fiskhest** [dokeraj/AndroTainer#18]
I have a portainer instance hosted at https://portainer.example.com that I can access and use through the web gui (https://portainer.example.com/#!/home)

When I try to login to that instance through the AndroTainer app using the root URL I get a popup saying `Server not permitting communication! Check URL.`

The portainer instance is hosted in a k3s-cluster exposed through an ingress using the nginx ingress-controller. I'm wondering if there's any specific headers the application requires to operate? Does it know how to follow redirects?

**Comment by dokeraj** [comment]
> I have a portainer instance hosted at https://portainer.example.com that I can access and use through the web gui (https://portainer.example.com/#!/home)
> 
> When I try to login to that instance through the AndroTainer app using the root URL I get a popup saying `Server not permitting communication! Check URL.`
> 
> The portainer instance is hosted in a k3s-cluster exposed through an ingress using the nginx ingress-controller. I'm wondering if there's any specific headers the application requires to operate? Does it know how to follow redirects?

Hi fiskhest,
I'm not sure what the issue might be. I also have my Portainer hosted behind nginx. The only difference is that I have Portainer hosted as subfolder (https://example.com/portainer). Also do you have password setup on Portainer (not sure if Portainer can be run without credentials :)). 

Can you try to run Portainer as subfolder?

**Comment by dokeraj** [comment]
@fiskhest 
I just switched Portainer from subfolder to subdomain (https://portainer.example.com) and I can login just fine. So you should make sure that you just type `https://portainer.example.com` in the login textbox, when logging in.

**Comment by fiskhest** [comment]
Hi @dokeraj , thank you for the swift response. :1st_place_medal: 

I'm attaching a screenshot of what I have in my app and how I login to the gui.

For webgui: I enter https://portainer.example.com in my address bar and am presented with the following login form that I input data and press login. 
![Screenshot_2021-03-05-38_2131x797](https://user-images.githubusercontent.com/26885267/110153659-a5f0c500-7de3-11eb-9acf-d8cc1d468869.png)

I am now presented with the dashboard
![Screenshot_2021-03-05-10_2399x942](https://user-images.githubusercontent.com/26885267/110153800-cd479200-7de3-11eb-9aaf-31680efcd287.png)

I open the app AndroTainer and fill it as follows
![Screenshot_20210305-102340](https://user-images.githubusercontent.com/26885267/110154560-afc6f800-7de4-11eb-95a9-29522c79665d.jpg)

and a small white bar is popped up on the bottom giving the message I put as issue title.

I'll see about exposing it under a subfolder instead of a subdomain, but I strongly doubt that is the issue seeing as you could go the other way. :)

**Comment by dokeraj** [comment]
Hi @fiskhest,
Yeah, I agree the problem you have, it won't be fixed if you use subfolder instead of subdomain. Unfortunately I'm busy atm with other projects, but I will try and find some free time to make a special version (for internal testing) and I will give you invite. In that version you will see the raw error, so then I will know how to tackle this login issue.

I will keep you posted.

**Comment by fiskhest** [comment]
Thanks for the update.

I see. Is there a technological reason for that? I would expect the portainer API to expose the same set of information no matter the underlying hypervisor or technology. I know you're unaffiliated, but portainer themselfs boasts to be a `open source tool for managing container-based software applications in Kubernetes, Docker, Docker Swarm, Azure ACI and edge environments.` It seems to me that this project is a AndroidDockerPortainer app than an android companion app for portainer. :-)

Perhaps it would be beneficial to point out in FAQ or readme that the app only supports Docker?

Thanks again for the assistance and efforts to try and resolve the issue  ! :100:

**Comment by dokeraj** [comment]
> 
> 
> Thanks for the update.
> 
> I see. Is there a technological reason for that? I would expect the portainer API to expose the same set of information no matter the underlying hypervisor or technology. I know you're unaffiliated, but portainer themselfs boasts to be a `open source tool for managing container-based software applications in Kubernetes, Docker, Docker Swarm, Azure ACI and edge environments.` It seems to me that this project is a AndroidDockerPortainer app than an android companion app for portainer. :-)
> 
> Perhaps it would be beneficial to point out in FAQ or readme that the app only supports Docker?
> 
> Thanks again for the assistance and efforts to try and resolve the issue ! 💯

Actually Portainer exposes all of its features through their API. The reason I have not implement Kubernetes is because I have no experience with managing Kubernetes environment. 
The reason why I created this app was to meet my needs for managing Docker containers :)
Thank you for pointing out this issue with Androtainer - I have updated the readme and description on the Play Store.

Cheers

**Comment by fiskhest** [comment]
Thanks for the update @dokeraj, hopefully it'll save you and somebody else an issue ticket. :+1:
