### ISSUE TITLE
Could you please support the "restart" operation to the container?

### ISSUE THREAD

**Issue by Zhao-Michael** [dokeraj/AndroTainer#34]
Hi Zarko,

I notice that some time my container happened to stop and can't be started again.
Then I had to restart the container to run it. But androtainer doesn't support the operation... I had to open my pc and restart it...😅

So, do you have any plan to supoort this operation?

Restart API: api/endpoints/2/docker/containers/(...container id..)/restart

Thanks,
Michael

**Comment by dokeraj** [comment]
Hey Michael,

What was the status that was shown in Androtainer, since I think that the
restart API is just using stop and start functions.

So you should also be able to do that through Androtainer.

Regards,
Zarko

**Comment by Zhao-Michael** [comment]
No, i can't start the stopped container. It shows "Error" after i try to click start.
![image](https://user-images.githubusercontent.com/15730936/142008879-f68994b0-b9e3-4b39-83ae-c7044946d64d.png)

![image](https://user-images.githubusercontent.com/15730936/142008949-a209c686-86d9-4aef-b772-3792a4907ca0.png)

And I also found that i cannot remove a stopped container. it shows "Error deleting  container! Please try again."

**Comment by Zhao-Michael** [comment]
It seems that the container has been deleted is still displayed in the list in Androtainer.
So I think maybe it is the reason why error.

**Comment by dokeraj** [comment]
Hmm, I will take a look at that endpoint and I will let you know. I'm still
baffled that restart is doing something different than regular stop/start.

**Comment by Zhao-Michael** [comment]
I am not sure about how restart works. But restart did let my app started.... and only stop/start can't work....😑🙃

**Comment by Zhao-Michael** [comment]
And I think that maybe recreate can be support also, in case of start/restart not working......

**Comment by dokeraj** [comment]
I will check that out too. Perhaps I will have more free time this weekend.

**Comment by dokeraj** [comment]
@Zhao-Michael I didn't have free time the past week, I will see if I can squeeze some time next week

**Comment by Zhao-Michael** [comment]
No problem, actually i don't think it's a very big issue. Please take your time~

**Comment by rezzalex** [comment]
> No problem, actually i don't think it's a very big issue. Please take your time~

Hello,

Same issue here, not able to start a container.

Thank you

**Comment by dokeraj** [comment]
@rezzalex can you tell me the version of docker and portainer you're using

**Comment by rezzalex** [comment]
> @rezzalex can you tell me the version of docker and portainer you're using

Docker CE 29.10.9
Portainer CE 2.11.1.R01

APIs are different according to docker and portainer version, right ?

**Comment by dokeraj** [comment]
@rezzalex yes, there might be some changes between versions, but are you sure about the version of Docker, since what I can see the latest version of docker is `20.10.14` https://docs.docker.com/engine/release-notes/

**Comment by rezzalex** [comment]
@dokeraj , typo, sorry, 20.10.9.r2

api version 1.41 (minimum version 1.12)

**Comment by dokeraj** [comment]
@rezzalex what happens if you try to stop and start the container using the Portainer web GUI? Does it still have error, or it let's you start it again?

**Comment by rezzalex** [comment]
working perfectly inside Portainer UI

**Comment by rezzalex** [comment]
> working perfectly inside Portainer UI

Hello @dokeraj ,

were you able to have a look at this restart issue ?

**Comment by fuxing-at** [comment]
Hallo!
I do have the same problem. I can't start a container when before stopped trought the app.
I'm running
app version 2.2 for
docker 20.10.9 with
Portainer 2.13.1
on a NAS (Asustor AS6202T)

**Comment by dokeraj** [comment]
@fuxing-at sorry I tried but I cannot reproduce this issue on my end.
@Zhao-Michael in the latest version - you can restart a container by long pressing the `START` / `STOP` button

**Comment by rezzalex** [comment]
> @fuxing-at sorry I tried but I cannot reproduce this issue on my end.
> @Zhao-Michael in the latest version - you can restart a container by long pressing the `START` / `STOP` button

@dokeraj 
I have tried with  my current version (2.2)... No restart as far as I can see.
What did I missed ?

**Comment by dokeraj** [comment]
There was a problem with publishing the new version (2.3) on playstore. It
should be live in a few hours. If you don't want to wait you can download
the .apk if you go to the releases page in the github repo.
