### ISSUE TITLE
Unable to connect to local instance

### ISSUE THREAD

**Issue by whyareallthegoodnamestaken** [dokeraj/AndroTainer#35]
Hey I am unable to connect to my local portainer instance. It just gives me the error "Wrong URL or service is down" even though I can reach the native WebUI.

Any ideas?

**Comment by dokeraj** [comment]
Hi,

What version of portainer do you use? I'm currently on 20.10.7
Also note, that androtainer doesn't support 2FA, only local accounts are supported.
Did you try to login using your local IP and port? Mine is 192.168.1.1:9500 (that is what you need to input into the URL field.

**Comment by hiasi-tierchen** [comment]
Hi,

i have the same problem:

![grafik](https://user-images.githubusercontent.com/4946634/147837139-940252c8-ce16-42fb-a45f-394e11c2ba3e.png)


<html><body>


 Version of portainer: | 20.10.12 (API: 1.41)
-- | --



</body>
</html>

![grafik](https://user-images.githubusercontent.com/4946634/147837061-dff030f8-0b73-4d64-b680-68558ae6867e.png)


Thank you!

**Comment by whyareallthegoodnamestaken** [comment]
I am at 20.10.11(API 1.41).

Indeed using localIP:port, not using MFA and using a non-administrator to log in.

Have a great new years eve.

**Comment by dokeraj** [comment]
Hmm I've never tried it with non admin user.
Do you use portainer with Docker or kubernetes?

And happy new year also!

**Comment by hiasi-tierchen** [comment]
Thank you very much,

but i have the same Problem with non-admin log in.
I use portainer with docker.

Happy new year also!

**Comment by dokeraj** [comment]
Hi and how many endpoints do you have?

**Comment by dokeraj** [comment]
Wait I think I got it. The URL must start with http:// or https://, so in
your case @haisi-tierchen you need to type:

http://192.168.17 <http://192.168.172>8.2:9443

**Comment by xaabi6** [comment]
I also had to use http to access my local docker instance, without it, it did not work

**Comment by whyareallthegoodnamestaken** [comment]
I also use Docker, I've tried http://IP:port, this gives me a different error than before. It now says: `"There are no Portainer endpoints listed!"`

**Comment by hiasi-tierchen** [comment]
It doesn't matter if I put http or https in front of it, it doesn't work.
But I get another error message:

Error message:
"Server not permitting communication! Check URL!"

**Comment by dokeraj** [comment]
@whyareallthegoodnamestaken can you send the response json of the endpoint `http://yourDomain/api/endpoints?limit=100&start=1` 
I'm mostly interested in the jsNumber field `Id` and the `URL` JsString.

**Comment by dokeraj** [comment]
@hiasi-tierchen That is weird, I will push a new version where the error will be displayed in the popup message, so we can see what it says.

**Comment by hiasi-tierchen** [comment]
@dokeraj Thank you very much!

**Comment by dokeraj** [comment]
@hiasi-tierchen no problem. I've pushed a new version on playstore (v2.0). You will be able to download it within the next few hours.

**Comment by hiasi-tierchen** [comment]
Thank you. I'll test it tomorrow

**Comment by hiasi-tierchen** [comment]
When i use the https-connection (Port 9443) this error message occures:
![grafik](https://user-images.githubusercontent.com/4946634/147891840-5ec5ad81-30e8-4acc-a8e5-15455594b46d.png)

When i use the http-connection (Port 9000) this error message occures:
![grafik](https://user-images.githubusercontent.com/4946634/147891860-06f9fdfa-a3c9-452b-98a9-a12120c1cd36.png)

**Comment by whyareallthegoodnamestaken** [comment]
Going to my instance at `http://yourIP:Port/api/endpoints?limit=100&start=1`

It gives me the following message:
 ```{"message":"A valid authorisation token is missing","details":"Unauthorized"}```

**Comment by dokeraj** [comment]
@whyareallthegoodnamestaken sorry I wasn't clear enough - here is what you need to do:
- On your desktop machine - Open chrome and go to the portainer login page (logout if you need to).
- Press F12 on your keyboard
- On the right you will see a new pane window: then select Network
- Then you login to portainer and you will see the `endpoints` API call. Click on it and you will see a list of endpoints. 
Here is a screenshot to make it more clea
![porta](https://user-images.githubusercontent.com/76596154/147916240-fed40e65-2489-4769-a523-bc0a44876538.png)
r

**Comment by dokeraj** [comment]
@hiasi-tierchen can you please send me the docker run command you use to spin up a new portainer container. 
Also can you do the steps I've told @whyareallthegoodnamestaken to do.
Thank you

**Comment by whyareallthegoodnamestaken** [comment]
I believe it is empty.

Both `endpoints?limit=100&start=0` and `endpoints?limit=100&start=1` have the output `No proporties`.

**Comment by dokeraj** [comment]
@whyareallthegoodnamestaken ok now I'm confused. I don't think that Portainer can display the containers if you don't specify which endpoint you want those containers to be listed from.

Can you also send me the docker run command you use to create the Portainer container. 
Also can you send a screenshot of what is displayed right after you login to Portainer (on Desktop of course). As you can see from my screenshot I've got one endpoint called `local`.

**Comment by whyareallthegoodnamestaken** [comment]
I also just have one endpoint/environment running with the name `local`. See screenshot below:
![Screenshot_20220103-190620_Chrome.jpg](https://user-images.githubusercontent.com/82374236/147964317-9d7535d5-e3b1-4aad-9682-c5adc04dba88.jpg)

I used `docker run -d -p 8000:8000 -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
` to run the Portainer instance.

**Comment by dokeraj** [comment]
@whyareallthegoodnamestaken @hiasi-tierchen here is a short video of how to check the response of the endpoints API: https://drive.google.com/file/d/1-4o-j5rTcX2wnshLeJKTF4DVKIraqAXY/view?usp=sharing

**Comment by whyareallthegoodnamestaken** [comment]
Thanks for the video, but must br a Chrome thing for me. I tried it Firefox and now I get an output in that file:
```
Object { Id: 2, Name: "local", Type: 1, … }


Id
2
Name
"local"
Type
1
URL
"unix:///var/run/docker.sock"
GroupId
1
PublicURL





```

**Comment by hiasi-tierchen** [comment]
Thank you for the video. 

Sorry for the late reply.
I don't have a lot of experience in docker. I'm a beginner.

Here is the screenshot:
![grafik](https://user-images.githubusercontent.com/4946634/147981275-24f0f442-a027-4a38-b5df-103892ccc46a.png)

Docker run command:
docker run -d -p 8000:8000 -p 9443:9443 --name portainer \
    --restart=always \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v portainer_data:/data \
    portainer/portainer-ce:2.11.0

**Comment by dokeraj** [comment]
@hiasi-tierchen @whyareallthegoodnamestaken can I suggest you use the following docker run command `docker run -d -p 9000:9000 --name portainer --restart unless-stopped -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest`.

You only need port 9000 (HTTP connection), since you access your portainer service through your local IP address. So when you login you should use _http://yourIP:9000_

Let me know if this helps.

**Comment by hiasi-tierchen** [comment]
@dokeraj I used your docker run command and the HTTP-connection.

At the first login, again the message popped up: "There are no Portainer endpoints listed!".
After that, I created a team and associated Team Members. 
Then I created a group associated the team and the environments "local"

Is it possible that this could be related to the above error?

Now i have access with all users (admin and non-admin).

It works with my docker run command, too. But only with "http://" (HTTP-connection)

It works!!!

Thank you very much

**Comment by dokeraj** [comment]
@hiasi-tierchen I've tested by creating a non-admin user. Yes you need to grant him privileges to be able to access the local endpoint. The admin has these rights from the get-go. I'm happy you resolved the issue.

**Comment by hiasi-tierchen** [comment]
:-) Thanks again!

**Comment by dokeraj** [comment]
@whyareallthegoodnamestaken did you manage to resolve your problem? If so I will go ahead and close this issue.

**Comment by whyareallthegoodnamestaken** [comment]
Yes I resolved my issue.

I had to create an usergroup and add this to the environment. 

To have visibility over the specific containers I also had to change the ownership of the container to the newly created usergroup.

Now the non-admin user only sees 1 of the 7 containers in the environment.

Thanks for your help.

**Comment by dokeraj** [comment]
@whyareallthegoodnamestaken Awesome! :)
