### ISSUE TITLE
Unable to login when oauth is configured

### ISSUE THREAD

**Issue by alsoGAMER** [dokeraj/AndroTainer#44]
Server response: Unknown error
Nginx reports no access to the endpoint and no errors.

Configuration quirk: I'm using cloudflare as reverse proxy and portainer is served through nginx on the same host.

**Comment by dokeraj** [comment]
Hi,

Is there a redirect when you are logging in using your browser?

**Comment by alsoGAMER** [comment]
Yes, it redirect me to the github login page.

**Comment by AMMJ93** [comment]
Same issue with Google OAuth

**Comment by dokeraj** [comment]
Sorry, I didn't understand your issue in the first place.

Androtainer doesn't support oauth. I was planning on implementing google
oauth, but I never got around to it.

Regards,
Zarko

**Comment by alsoGAMER** [comment]
> Androtainer doesn't support oauth.

I didn't know that, cause you haven't specified this anywhere.
Hope that someday this issue will be solved.

**Comment by dokeraj** [comment]
Yes, you are right. I will add it in the description on playstore.

**Comment by AMMJ93** [comment]
Too bad! Thanks for replying.
