### ISSUE TITLE
Wishlist - Supporting Widgets

### ISSUE THREAD

**Issue by thefunkygibbon** [dokeraj/AndroTainer#47]
Would be fantastic to be able to have a widget/shortcut of some kind on my phones home screen to start (or restart, stop) a container (or group of containers?)  would also be cool to have a widget that shows the stats/status of a/all/group container/s 

thanks for the great app though, it really comes in handy with my home setup

**Comment by Nazgile94** [comment]
+1 for that

**Comment by dokeraj** [comment]
I'm sorry, but I don't have any plans to support widgets in the future.
