### ISSUE TITLE
Support for older android versions

### ISSUE THREAD

**Issue by fischer-felix** [dokeraj/AndroTainer#48]
I've just noticed that AndroTainer is only built for Android 10 and up, so since my phone will sadly not get past 9, I was wondering what the reason for that is.

Is there some technical limitation or would changing the minimum API version in Android Studio fix this?

**Comment by dokeraj** [comment]
@fischer-felix when I started this project I wasn't going to expose it to the public, so Android 10 fitted my needs. Now there are technical difficulties to make it support older versions of android - sorry.
